ALTER TABLE efetivo_pm ADD COLUMN IF NOT EXISTS data_taf_tat DATE;
ALTER TABLE efetivo_pm ADD COLUMN IF NOT EXISTS taf           TEXT;
ALTER TABLE efetivo_pm ADD COLUMN IF NOT EXISTS tat           TEXT;
